apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec-ori
spec:
  containers:
    - image: nginx
      name: use-pv
      volumeMounts:
        - mountPath: /tmp
          name: my-pod-volume
      resources: {}
  volumes:
    - name: my-pod-volume
      persistentVolumeClaim:
        claimName: my-volume-claim

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

