apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  #namespace: pvc-demo
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
