apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-claim
    #namespace: pvc-demo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
