apiVersion: v1
kind: Pod
metadata:
  name: busybox-dns
  labels:
    resolve: this
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
    imagePullPolicy: IfNotPresent

